/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.GeneroController;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import Models.GeneroModel;
import javax.swing.DefaultListModel;
import Controllers.CDSController;
import Models.CDSModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Botzera
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    GeneroController genC= new GeneroController();
    CDSController CDSC = new CDSController();
    public Main() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListGeneros = new javax.swing.JList();
        btnCarregarCDS = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCDS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        ListGeneros.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(ListGeneros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 200, 400);

        btnCarregarCDS.setText("Carregar CDS com base no genero");
        btnCarregarCDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCDSActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarregarCDS);
        btnCarregarCDS.setBounds(20, 20, 240, 50);

        tableCDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Interprete", "Genero", "Preco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableCDS);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(240, 80, 453, 403);

        setBounds(0, 0, 732, 532);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verify(){
        if(ListGeneros.getSelectedValue().equals(null) || ListGeneros.getSelectedValue().equals("") || ListGeneros.getSelectedValue() == null || ListGeneros.getSelectedValue() == ""){
            return true;
        }else{
            return false;
        }
    }
    
    private void btnCarregarCDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCDSActionPerformed
        if(this.verify()){
            JOptionPane.showMessageDialog(null, "To do this action, please, select a genre first ");
        }else{
            GeneroModel genre = new GeneroModel(ListGeneros.getSelectedValue().toString());
            CDSModel cd = new CDSModel(0, "", "", genre, 0.0f);
            ArrayList<CDSModel> allCDS = CDSC.show(cd);
            DefaultTableModel cdModel = (DefaultTableModel) tableCDS.getModel();
            for(int i = 0; i < allCDS.size(); i++){
                cdModel.addRow(new Object[]{allCDS.get(i).getCodigo(), allCDS.get(i).getTitulo(), allCDS.get(i).getInterprete(), allCDS.get(i).getGenero().toString(), allCDS.get(i).getPreco()});
            }
            tableCDS.setModel(cdModel);
        }
    }//GEN-LAST:event_btnCarregarCDSActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<GeneroModel> virtualGen = genC.index();
        String a = "";
        DefaultListModel genModel = new DefaultListModel();
        for(int i = 0;i < virtualGen.size(); i++){
           genModel.addElement(virtualGen.get(i).getGenero());
        }
        
        ListGeneros.setModel(genModel);
      
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListGeneros;
    private javax.swing.JButton btnCarregarCDS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableCDS;
    // End of variables declaration//GEN-END:variables
}
