/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcklinkedlist;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Botzera
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }
    
    LinkedList Link = new LinkedList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Titulo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(61, 74, 60, 24);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(140, 70, 300, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Ano");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 60, 24);
        getContentPane().add(txtAno);
        txtAno.setBounds(140, 120, 300, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Autor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 30, 60, 24);
        getContentPane().add(txtAutor);
        txtAutor.setBounds(140, 20, 300, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Editora");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 70, 24);
        getContentPane().add(txtEditora);
        txtEditora.setBounds(140, 170, 300, 30);

        jButton1.setText("Extrair livros depois de 2002");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 240, 200, 40);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(20, 240, 110, 40);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(140, 240, 110, 40);

        jButton4.setText("Extrair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 240, 110, 40);

        jScrollPane1.setAutoscrolls(true);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setLineWrap(true);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 560, 180);

        setBounds(0, 0, 613, 534);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verify(){
        if(Integer.parseInt(txtAno.getText()) == 0 ||
           txtAutor.getText().equalsIgnoreCase(null) || txtAutor.getText().equalsIgnoreCase("") ||
           txtEditora.getText().equalsIgnoreCase(null) || txtEditora.getText().equalsIgnoreCase("") ||
           txtTitulo.getText().equalsIgnoreCase(null) || txtTitulo.getText().equalsIgnoreCase("")){
            return true;
        }else{
            return false;
        }
    }
    
    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if(this.verify()){
            JOptionPane.showMessageDialog(null, "To continue with this action, please, complete all the fields ");
        }else{
            Livro book = new Livro(txtTitulo.getText(), txtAutor.getText(), Integer.parseInt(txtAno.getText()), txtEditora.getText());
            if(Link.peekFirst() == null){
                Link.addFirst(book);
            }else{
                Link.addLast(book);
            }
            
            JOptionPane.showMessageDialog(null, "Book inserted with success ");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        if(Link.isEmpty()){
            txtArea.setText("Any book inserted yet ");
        }
        else{
            txtArea.setText("");
            Object[] allBooks = Link.toArray();
            for(int i = 0; i < allBooks.length; i++){
                if(allBooks[i] instanceof Livro){
                    Livro book = (Livro) allBooks[i];
                    txtArea.setText(txtArea.getText() + book.toString() + " \n");
                }
            }
        } 
    }//GEN-LAST:event_btnListarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(Link.isEmpty()){
            txtArea.setText("Any book inserted still to delete ");
        }else{
            txtArea.setText("");
            Livro book = (Livro) Link.removeFirst();
            txtArea.setText(book.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Link.isEmpty()){
            txtArea.setText("Any book inserted still to create a another queue ");
        }else{
            LinkedList newFireLink = new LinkedList();
            Object[] allBooks = Link.toArray();
            txtArea.setText("");
            for(int i = 0; i < allBooks.length; i++){
                Livro book = (Livro) allBooks[i];
                if(book.getAno_lancamento() > 2002){
                    if(newFireLink.isEmpty()){
                        newFireLink.addFirst(book);
                    }else{
                        newFireLink.addLast(book);
                    }
                }
            }
            
            Object[] BooksOf2003 = newFireLink.toArray();
            for(int i = 0; i < BooksOf2003.length; i++){
                Livro book = (Livro) BooksOf2003[i];
                
                txtArea.setText(txtArea.getText() + book.toString() + "\n");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
