package Views;

import Models.EstadoModel;
import Controllers.EstadoController;
import java.util.ArrayList;
import Controllers.CidadesController;

public class Form2 extends javax.swing.JFrame {

    /**
     * Creates new form Form2
     */
    public Form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSiglas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        comboSiglas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " " }));
        comboSiglas.setToolTipText("");
        comboSiglas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSiglasItemStateChanged(evt);
            }
        });
        getContentPane().add(comboSiglas);
        comboSiglas.setBounds(70, 80, 60, 26);

        txtBox.setEditable(false);
        txtBox.setColumns(20);
        txtBox.setLineWrap(true);
        txtBox.setRows(5);
        jScrollPane1.setViewportView(txtBox);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 60, 240, 240);

        jLabel1.setText("Selecione o estado desejado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 180, 16);

        jLabel2.setText("Veja as cidades que ele tem");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 30, 170, 16);

        setBounds(0, 0, 586, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        EstadoController ec = new EstadoController();
        ArrayList<EstadoModel> array_em = new ArrayList<>();
        
        array_em = ec.index();
        
        for(int i = 0; i < array_em.size(); i++){
            comboSiglas.addItem(array_em.get(i).getSigla());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void comboSiglasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSiglasItemStateChanged
        CidadesController cc =new CidadesController();
        ArrayList<String> city = new ArrayList<>();
        
        city = cc.index(comboSiglas.getSelectedItem().toString());
        
        String msg = "";
        for(int i = 0; i < city.size(); i++){
            msg += city.get(i) + " \n";
        }
        
        txtBox.setText(msg);
    }//GEN-LAST:event_comboSiglasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboSiglas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtBox;
    // End of variables declaration//GEN-END:variables
}
