package Views;

import Models.AlunoModel;
import Controllers.AlunoController;
import javax.swing.JOptionPane;

public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }
    AlunoController ac = new AlunoController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtRGM = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("RGM: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 50, 16);

        jLabel2.setText("Estado");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 210, 60, 16);

        jLabel3.setText("Nome: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 70, 16);

        jLabel4.setText("Endereço: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 80, 16);

        jLabel5.setText("Cidade: ");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 60, 16);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(160, 210, 160, 24);
        getContentPane().add(txtRGM);
        txtRGM.setBounds(160, 30, 160, 24);
        getContentPane().add(txtNome);
        txtNome.setBounds(160, 80, 160, 24);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(160, 130, 160, 24);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(160, 170, 160, 24);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(230, 250, 90, 32);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(30, 250, 77, 32);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(130, 250, 77, 32);

        jButton1.setText("Exercicio 02 ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 120, 120, 32);

        setBounds(0, 0, 568, 339);
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean verify(){
        if(txtRGM.getText() == null || txtRGM.getText() == "" ||
            txtNome.getText() == null || txtNome.getText() == "" ||
            txtCidade.getText() == null || txtCidade.getText() == "" ||
            txtEndereco.getText() == null || txtEndereco.getText() == "" ||
            txtEstado.getText() == null || txtEstado.getText() == ""){
            return false;
        }else{
            return true;
        }
    }
    
    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if(!this.verify()){
            JOptionPane.showMessageDialog(null, "Para continuar, complete todos os campos ");
        }else{
            AlunoModel am = new AlunoModel(txtRGM.getText(), txtNome.getText(), txtEndereco.getText(), txtCidade.getText(), txtEstado.getText());
            ac.store(am);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(txtRGM.getText() == null || txtRGM.getText() == ""){
            JOptionPane.showMessageDialog(null, "Insira pelo menos o rgm para deletar o aluno");
        }
        else{
            AlunoModel am = new AlunoModel(txtRGM.getText(), txtNome.getText(), txtEndereco.getText(), txtCidade.getText(), txtEstado.getText());
            ac.destroy(am);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if(!this.verify()){
            JOptionPane.showMessageDialog(null, "Para continuar, complete todos os campos ");
        }else{
            AlunoModel am = new AlunoModel(txtRGM.getText(), txtNome.getText(), txtEndereco.getText(), txtCidade.getText(), txtEstado.getText());
            ac.update(am);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Form2 f2 = new Form2();
        f2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRGM;
    // End of variables declaration//GEN-END:variables
}
