package views;

/**
 * @author Ledón
 */

import controllers.alunoController;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.alunos;

public class JanelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastro
     */
    public JanelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtaListaAluno = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRGM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCursoAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdadeAluno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnStore = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDestroy = new javax.swing.JButton();
        btnIndex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos e Consultas");

        txtaListaAluno.setColumns(20);
        txtaListaAluno.setLineWrap(true);
        txtaListaAluno.setRows(5);
        txtaListaAluno.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtaListaAluno);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("RGM:");

        txtRGM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGMActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do aluno:");

        jLabel3.setText("Curso (abrev.):");

        jLabel4.setText("Idade do aluno:");
        jLabel4.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnStore.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnStore.setText("<html>Cadastrar <br/>novo aluno</html>");
        btnStore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("Alterar aluno (RGM acima)");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDestroy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDestroy.setText("Eliminar aluno (RGM acima)");
        btnDestroy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestroyActionPerformed(evt);
            }
        });

        btnIndex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIndex.setText("Consultar alunos (do curso acima)");
        btnIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIndex)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnDestroy))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDestroy))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnIndex)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtRGM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdadeAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(813, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verify(){
        if(txtRGM.getText().equalsIgnoreCase(null)|| txtRGM.getText().equalsIgnoreCase("") ||
           txtNomeAluno.getText().equalsIgnoreCase(null) || txtNomeAluno.getText().equalsIgnoreCase("")||
           Integer.parseInt(txtIdadeAluno.getText()) <= 0 ||
           txtCursoAluno.getText() ==  null || txtCursoAluno.getText().equalsIgnoreCase("")){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean verifyRGM(){
        if(txtRGM.getText().equalsIgnoreCase("") || txtRGM.getText().equalsIgnoreCase(null)){
            return true;
        }
        else{
            return false;
        }
    }
    
    private boolean verifyCourse(){
        if(txtCursoAluno.getText().equalsIgnoreCase(null) || txtCursoAluno.getText().equalsIgnoreCase("")){
            return true;
        }
        else{
            return false;
        }
    }
    
    private void txtRGMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGMActionPerformed

    private void btnStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreActionPerformed
        if(this.verify()){
            JOptionPane.showMessageDialog(null, "Please, to continue with this action, complete all the fields first");
        }else{
            alunoController ac = new alunoController();
            alunos student = new alunos(txtRGM.getText(), txtNomeAluno.getText(),Integer.parseInt(txtIdadeAluno.getText()), txtCursoAluno.getText());
            try {
                
                ac.store(student);
                JOptionPane.showMessageDialog(null, "Student inserted with success! ");
            } catch (ClassNotFoundException ex) {
                throw new RuntimeException("Error in create a new Student" + ex);
            }
        }
    }//GEN-LAST:event_btnStoreActionPerformed

    private void btnIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexActionPerformed
        if(this.verifyCourse()){
            JOptionPane.showMessageDialog(null, "Please, to continue with this action, complete the field of course ");
        }
        else{
            txtaListaAluno.setText("");
            alunos student = new alunos();
            student.setCurso(txtCursoAluno.getText());
            student.setIdade(0);
            student.setNome("");
            student.setRGM("");
            alunoController ac = new alunoController();
            
            try {
                ArrayList<alunos> allStudents = ac.index(student);
                
                for(int i = 0; i < allStudents.size(); i++){
                    txtaListaAluno.setText(txtaListaAluno.getText() + allStudents.get(i).getRGM() + " | " 
                            + allStudents.get(i).getNome() + " | " + allStudents.get(i).getIdade() 
                            + " | " + allStudents.get(i).getCurso() + "\n");
                }
                
            } catch (ClassNotFoundException ex) {
                throw new RuntimeException("Error to list the students " + ex);
            }
        }
    }//GEN-LAST:event_btnIndexActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(this.verify()){
            JOptionPane.showMessageDialog(null, "To continue with this action, please complete all the fields ");
        }else{
            alunos student = new alunos(txtRGM.getText(), txtNomeAluno.getText(),Integer.parseInt(txtIdadeAluno.getText()), txtCursoAluno.getText());
            alunoController ac = new alunoController();
            
            try {
                ac.update(student);
                JOptionPane.showMessageDialog(null, "Student updated with success ");
            } catch (ClassNotFoundException ex) {
                throw new RuntimeException("Error in update a student" + ex);
            }
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDestroyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestroyActionPerformed
        if(this.verifyRGM()){
            JOptionPane.showMessageDialog(null, "To continue, please insert the field of RGM ");
        }else{
            alunos student = new alunos();
            student.setRGM(txtRGM.getText());
            student.setCurso("");
            student.setNome("");
            student.setIdade(0);
            
            alunoController ac = new alunoController();
            try {
                ac.destroy(student);
                JOptionPane.showMessageDialog(null, "Student deleted with success! ");
            } catch (ClassNotFoundException ex) {
                throw new RuntimeException("Error to delete a student "+ ex);
            }
        }
    }//GEN-LAST:event_btnDestroyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestroy;
    private javax.swing.JButton btnIndex;
    private javax.swing.JButton btnStore;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCursoAluno;
    private javax.swing.JTextField txtIdadeAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtRGM;
    private javax.swing.JTextArea txtaListaAluno;
    // End of variables declaration//GEN-END:variables
}
